### ISSUE TITLE
Create a new cloud connector for Message Hub

### ISSUE THREAD

**Issue by FcoJavierSainz** [IBM-Bluemix/bluemix-cloud-connectors#7]
With the new Spring cloud component cloud-streams is complex to connect with Kafka Server, for example set this variable `spring.cloud.stream.kafka.binder.auto-create-topics=false` because MH does not allow to access to Zookeeper

**Comment by BarDweller** [comment]
Cleaning up old issues... 

There are no current plans to add a new cloud connector for Message Hub (now Event Streams).  It may be worth looking at the https://github.com/pivotal-cf/java-cfenv as it's likely any future efforts would be toward supporting CfEnvProcessors rather than cloud connectors.
